services:
  ad-task-3:
    build:
      context: .
    container_name: ad-task-3-service
    ports:
      - "8080:8000"
    develop:
      watch:
        - path: .
          target: /var/www/html
          action: sync
        - path: ./composer.json
          action: rebuild
        - path: ./composer.lock
          action: rebuild
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: ad-task-3-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
      MONGO_INITDB_DATABASE: cejibase
    ports:
      - "27122:27017"
    volumes:
      - ad-task-3-mongodb:/data/db/mongodb

  postgresql:
    image: postgres:15
    container_name: ad-task-3-postgresql
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cejibase
    ports:
      - "5126:5432"
    volumes:
      - ad-task-3-postgresql:/data/db/postgresql

volumes:
  ad-task-3-mongodb:
    driver: local
  ad-task-3-postgresql:
    driver: local
